In [2]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
import pandas as pd

In [3]:
df=pd.read_csv('spam.csv')


In [4]:
df_spam=df[df['Category']=='spam']
df_ham = df[df['Category']=='ham']
df_downsample=df_ham.sample(df_spam.shape[0])
df_balace=pd.concat([df_spam,df_downsample])
df_balace['Category'].value_counts()

spam    747
ham     747
Name: Category, dtype: int64

In [5]:
df_balace['spam']=df_balace['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [52]:
X=df_balace['Message'].values
X

array(["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       "FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, £1.50 to rcv",
       'WINNER!! As a valued network customer you have been selected to receivea £900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.',
       ..., 'S s..first time..dhoni rocks...', 'K.k:)when are you going?',
       "Sorry, I'll call later in meeting"], dtype=object)

In [71]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,df_balace['spam'].values, stratify=df_balace['spam'].values)

In [49]:
bert_process=hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")

In [50]:
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

ResourceExhaustedError: OOM when allocating tensor with shape[768,12,64] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu [Op:RestoreV2]

In [ ]:
def  get_embeddings(data):
    embeds=bert_process(data)
    #print(embeds)
    print(bert_encoder(embeds))
    return bert_encoder(embeds)['pooled_output'] 

get_embeddings(['hey everyone','hello all'])

{'encoder_outputs': [<tf.Tensor: shape=(1, 128, 768), dtype=float32, numpy=
array([[[ 0.18258475,  0.043331  , -0.07490037, ..., -0.07460802,
          0.09463173,  0.05395118],
        [-0.13750911,  1.1837007 ,  0.8106904 , ...,  0.7737527 ,
          0.5001144 ,  0.7895102 ],
        [-1.0307124 ,  0.9462978 , -1.1627166 , ...,  0.5497099 ,
          1.5537874 ,  0.07339209],
        ...,
        [-0.13697551, -0.19398455,  0.69094   , ...,  0.42719984,
         -0.32810342,  0.0261852 ],
        [-0.21351264, -0.21979864,  0.5582045 , ...,  0.45690247,
         -0.24296364, -0.04953255],
        [-0.12475335, -0.13917261,  0.56713367, ...,  0.7405346 ,
         -0.53513354, -0.10737729]]], dtype=float32)>, <tf.Tensor: shape=(1, 128, 768), dtype=float32, numpy=
array([[[ 0.04922761, -0.16608328, -0.13908988, ...,  0.01934348,
          0.09241388,  0.07489423],
        [ 0.27870086,  1.322284  ,  1.6214643 , ...,  0.6346986 ,
          0.45272478,  0.34086454],
        [-1.1390259 ,

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[-8.79564106e-01, -3.10086727e-01, -2.75275707e-01,
         7.12899506e-01,  2.73447126e-01, -1.18463024e-01,
         9.28399742e-01,  1.90343827e-01, -1.35474637e-01,
        -9.99900460e-01, -1.12889506e-01,  6.67466402e-01,
         9.81095791e-01,  4.29527350e-02,  9.39543426e-01,
        -6.05243504e-01, -1.35918975e-01, -5.16092718e-01,
         3.08636129e-01, -6.71994030e-01,  6.21907949e-01,
         9.97073293e-01,  5.26340306e-01,  2.09130600e-01,
         3.14766765e-01,  8.29339743e-01, -6.86056495e-01,
         9.44895923e-01,  9.51779783e-01,  6.29515886e-01,
        -6.99968398e-01,  1.13651372e-01, -9.84361708e-01,
        -1.46602988e-01, -2.00023204e-01, -9.82620955e-01,
         2.27872580e-01, -7.77170956e-01,  4.11729701e-02,
        -8.58599041e-03, -9.11747277e-01,  2.09130436e-01,
         9.99270439e-01, -4.25153971e-01,  6.97592795e-02,
        -2.65966743e-01, -9.99996185e-01,  1.66474819e-01,
      

In [ ]:
o=get_embeddings(['mango','hell','elon','banana'])

{'encoder_outputs': [<tf.Tensor: shape=(4, 128, 768), dtype=float32, numpy=
array([[[ 1.23324566e-01, -5.99631481e-03, -1.10136986e-01, ...,
         -6.66367263e-02,  3.06841284e-02, -3.92323509e-02],
        [ 5.75367033e-01,  1.14655697e+00, -1.11665690e+00, ...,
         -2.68816471e-01, -5.02158940e-01, -3.97919327e-01],
        [-3.00874025e-01,  1.21090055e-01, -8.61611813e-02, ...,
         -2.05432743e-01,  8.56340230e-01, -7.53250346e-02],
        ...,
        [-4.99372184e-02, -2.73006320e-01,  6.95585251e-01, ...,
          4.91894424e-01, -3.31998676e-01, -8.90660509e-02],
        [-1.45278484e-01, -2.83911288e-01,  5.64822853e-01, ...,
          5.01699805e-01, -2.39966094e-01, -1.79773167e-01],
        [ 2.14024633e-03, -1.86198458e-01,  5.81709027e-01, ...,
          8.32575738e-01, -5.70752800e-01, -2.63858229e-01]],

       [[ 2.33758688e-01,  1.40291989e-01, -9.31285396e-02, ...,
          7.53340125e-03,  7.04540759e-02, -3.10710967e-02],
        [ 2.32922888e+00,  

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity([o[1]],[o[2]])

array([[0.9864669]], dtype=float32)

In [ ]:
from tensorflow.keras.models import Model

In [ ]:
from tensorflow.keras.layers import Input,Dropout,Dense

In [77]:
inputs=Input(shape=(),dtype=tf.string,name='text')
preprocessed_text=bert_process(inputs)
encoder=bert_encoder(preprocessed_text)


drop=Dropout(0.2,name='dropout')(encoder['pooled_output'])
output=Dense(2,activation='softmax',name='outut')(drop)




In [78]:
model=Model(inputs=[inputs],outputs=[output])

In [79]:
model.summary()

Model: "model_6"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 text (InputLayer)              [(None,)]            0           []                               
                                                                                                  
 keras_layer_2 (KerasLayer)     {'input_word_ids':   0           ['text[0][0]']                   
                                (None, 128),                                                      
                                 'input_type_ids':                                                
                                (None, 128),                                                      
                                 'input_mask': (Non                                               
                                e, 128)}                                                    

In [80]:
model.compile(optimizer='adam',loss=tf.keras.losses.CategoricalCrossentropy(),metrics=[tf.keras.metrics.Accuracy(),tf.keras.metrics.Precision(),tf.keras.metrics.Recall()])

In [81]:
y_train=tf.keras.utils.to_categorical(y_train)

In [83]:
model.fit(X_train,y_train,epochs=10)

Epoch 1/10
35/35 [==============================] - 24s 674ms/step - loss: 0.5655 - accuracy: 0.0000e+00 - precision_7: 0.7152 - recall_7: 0.7152
Epoch 2/10
35/35 [==============================] - 23s 670ms/step - loss: 0.4330 - accuracy: 0.0000e+00 - precision_7: 0.8188 - recall_7: 0.8188
Epoch 3/10
35/35 [==============================] - 23s 669ms/step - loss: 0.3716 - accuracy: 0.0000e+00 - precision_7: 0.8554 - recall_7: 0.8554
Epoch 4/10
35/35 [==============================] - 24s 674ms/step - loss: 0.3410 - accuracy: 0.0000e+00 - precision_7: 0.8696 - recall_7: 0.8696
Epoch 5/10
35/35 [==============================] - 23s 669ms/step - loss: 0.3282 - accuracy: 0.0000e+00 - precision_7: 0.8786 - recall_7: 0.8786
Epoch 6/10
35/35 [==============================] - 23s 671ms/step - loss: 0.2940 - accuracy: 0.0000e+00 - precision_7: 0.8938 - recall_7: 0.8938
Epoch 7/10
35/35 [==============================] - 24s 672ms/step - loss: 0.2678 - accuracy: 0.0000e+00 - precision_7: 0.90

In [66]:
model.evaluate(X_test, tf.keras.utils.to_categorical(y_test))

12/12 [==============================] - 10s 644ms/step - loss: 0.2618 - accuracy: 0.0000e+00 - precision_4: 0.9305 - recall_4: 0.9305


[0.26181328296661377, 0.0, 0.9304812550544739, 0.9304812550544739]

In [88]:
pred=model.predict(X_test)

12/12 [==============================] - 9s 651ms/step


In [93]:
from sklearn.metrics import classification_report


In [110]:
import numpy as np
y_pred=[]
for i in range(len(pred)):
    y_pred.append(np.argmax(pred[i]))

In [111]:
y_pred=np.array(y_pred)

In [112]:
y_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,

In [115]:
print(classification_report(y_test,y_pred))
#y_pred.shape

              precision    recall  f1-score   support

           0       0.94      0.96      0.95       187
           1       0.96      0.94      0.95       187

    accuracy                           0.95       374
   macro avg       0.95      0.95      0.95       374
weighted avg       0.95      0.95      0.95       374

